# Recipient aliases. Encrypt with: gpg --encrypt -r <alias> --armor

# ======================================================================
# Parsa's keys
# ======================================================================
group parsa = 20896D6FF3927E926A2EF574FFB2FE0B3E3CD970 # gitleaks:allow
group parsa-ledger = 789B9333FDE3939A734C538510D5FB230E4B6C59 # gitleaks:allow
